# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.
#
# This Blueprint uses free instance types (specified by
# `plan`) for both the web service and the database. You
# can upgrade to paid instance types at any time to
# increase resources.

services:
  - type: web
    name: n8n-free
    runtime: image
    plan: free
    image:
      url: docker.io/n8nio/n8n:latest
    disk:
      name: n8n-data
      mountPath: /home/node
      sizeGB: 1
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: your-username
      - key: N8N_BASIC_AUTH_PASSWORD
        value: your-password
      - key: WEBHOOK_TUNNEL_URL
        value: https://your-subdomain.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://your-subdomain.onrender.com

databases:
  - name: n8n-db
    plan: free


databases:
  - name: n8n-db
    plan: free
    # The free instance type is limited to 1 GB of disk
    # space.
    #
    # If you later upgrade to a paid instance type, you can
    # increase the disk size to any multiple of 5 GB by
    # setting the `diskSizeGB` property.
    #
    # diskSizeGB: 5
