# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.
#
# This Blueprint uses free instance types (specified by
# `plan`) for both the web service and the database. You
# can upgrade to paid instance types at any time to
# increase resources.



databases:
  - name: n8n-db
    plan: free
    # The free instance type is limited to 1 GB of disk
    # space.
    #
    # If you later upgrade to a paid instance type, you can
    # increase the disk size to any multiple of 5 GB by
    # setting the `diskSizeGB` property.
    #
    # diskSizeGB: 5
